import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  CheckCircle2, XCircle, AlertTriangle, ShieldCheck, Download, Smartphone,
  Globe, FileText, Lock, Sparkles, Copy, Check, ExternalLink, X, Rocket
} from 'lucide-react';
import { CitizenState } from '../types';

interface AppStoreLaunchModalProps {
  isOpen: boolean;
  onClose: () => void;
  citizenState: CitizenState;
}

export const AppStoreLaunchModal: React.FC<AppStoreLaunchModalProps> = ({
  isOpen,
  onClose,
  citizenState
}) => {
  const [activeTab, setActiveTab] = useState<'audit' | 'privacy_policy' | 'metadata' | 'export_compliance'>('audit');
  const [copiedField, setCopiedField] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleCopy = (text: string, fieldName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleDownloadPrivacyPolicy = () => {
    const text = `# PRIVACY POLICY FOR BLURBUBBLE PRIVACY SHIELD
Last Updated: ${new Date().toISOString().split('T')[0]}

1. OVERVIEW & DECENTRALIZED ARCHITECTURE
BlurBubble ("the Application") is an offline-first, client-side tactical privacy shield designed to emit RFC-9402 compliance signals and obscure personal biometric data locally on your device.

2. DATA COLLECTION & STORAGE
- NO PERSONAL DATA IS COLLECTED OR TRANSMITTED TO EXTERNAL SERVERS.
- All Bluetooth Low Energy (BLE) rotation identifiers, face hash obfuscation settings, and local geofence perimeters are stored exclusively in your browser's local storage (localStorage).
- No user account creation, phone number, or email registration is required.

3. HARDWARE PERMISSIONS & USAGE
- Camera: Used exclusively for real-time local optical censorship (smart glasses HUD). Video frames never leave your local device memory.
- Microphone: Used exclusively for local acoustic spectrum analysis and ultrasonic frequency generation. Audio streams are processed live in-memory and immediately discarded.
- Geolocation: Used exclusively for calculating distance relative to user-defined safe zones and stationary perimeters on local maps.

4. CRYPTOGRAPHIC PROOFS & RFC-9402
- All opt-out certificates and timestamped audit logs generated by the app are cryptographically signed locally using Ed25519/SHA-256 routines.

5. CONTACT
For questions regarding BlurBubble's open-source privacy standards, visit:
https://github.com/blurbubble-privacy/rfc9402-standard
`;

    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'PRIVACY_POLICY_BLURBUBBLE.md';
    a.click();
    URL.revokeObjectURL(url);
  };

  const appStoreMetadata = {
    appName: "BlurBubble Privacy Shield",
    subtitle: "Stop Recording Me - RFC-9402 Signal Manager",
    primaryCategory: "Utilities",
    secondaryCategory: "Security",
    ageRating: "4+ (No Unrestricted Web Access)",
    keywords: "privacy shield, anti recording, BLE beacon, RFC-9402, smart glasses, biometric protection, camera censorship",
    promotionalText: "Take control of your personal privacy. Broadcast decentralized RFC-9402 opt-out signals against unauthorized smart cameras and AI recording arrays.",
    privacyNutritionLabel: "Data Not Collected - The developer does not collect any data from this app."
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
      <motion.div 
        initial={{ scale: 0.95, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.95, opacity: 0 }}
        className="relative w-full max-w-4xl max-h-[90vh] bg-slate-950 border border-emerald-500/30 rounded-2xl shadow-2xl overflow-hidden flex flex-col glow-emerald"
      >
        {/* Header Bar */}
        <div className="flex items-center justify-between p-4 bg-slate-900/90 border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-emerald-500/10 border border-emerald-500/30 rounded-xl">
              <Rocket className="w-5 h-5 text-emerald-400" />
            </div>
            <div>
              <h2 className="text-base font-black text-white flex items-center gap-2">
                BlurBubble App Store Launch Readiness Center
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                  READY FOR SUBMISSION
                </span>
              </h2>
              <p className="text-xs text-slate-400">Pre-flight diagnostics & metadata for Apple App Store, Google Play Console & PWA Stores</p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white bg-slate-900 border border-slate-800 rounded-lg cursor-pointer transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex items-center gap-2 px-4 py-2 bg-slate-900/40 border-b border-slate-850 overflow-x-auto text-xs font-mono font-bold">
          {[
            { id: 'audit', label: '✅ Launch Audit Checklist', icon: CheckCircle2 },
            { id: 'privacy_policy', label: '📜 Privacy Policy Generator', icon: Lock },
            { id: 'metadata', label: '📱 App Store Metadata', icon: Smartphone },
            { id: 'export_compliance', label: '🛡️ Export Compliance (EAR99)', icon: ShieldCheck }
          ].map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id as any)}
                className={`px-3 py-1.5 rounded-lg transition-all flex items-center gap-1.5 whitespace-nowrap cursor-pointer ${
                  activeTab === tab.id
                    ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Modal Body */}
        <div className="p-5 overflow-y-auto space-y-5 flex-1 text-slate-200">
          {activeTab === 'audit' && (
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="p-3.5 rounded-xl bg-slate-900/80 border border-emerald-500/30 space-y-2">
                  <div className="flex items-center gap-2 font-mono text-xs font-bold text-emerald-400">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span>PWA Manifest & Web App Standards</span>
                  </div>
                  <ul className="text-xs text-slate-300 space-y-1 font-mono list-disc list-inside">
                    <li>manifest.webmanifest configured</li>
                    <li>Display mode: standalone</li>
                    <li>Theme color: #020617</li>
                    <li>Responsive Mobile Touch Targets (&gt;44px)</li>
                  </ul>
                </div>

                <div className="p-3.5 rounded-xl bg-slate-900/80 border border-emerald-500/30 space-y-2">
                  <div className="flex items-center gap-2 font-mono text-xs font-bold text-emerald-400">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span>Hardware Permissions Attestation</span>
                  </div>
                  <ul className="text-xs text-slate-300 space-y-1 font-mono list-disc list-inside">
                    <li>Camera (Local Smart Glasses HUD)</li>
                    <li>Microphone (In-memory Audio Lab)</li>
                    <li>Geolocation (Local Map Perimeters)</li>
                    <li>Vibration API (Haptic Feedback)</li>
                  </ul>
                </div>

                <div className="p-3.5 rounded-xl bg-slate-900/80 border border-emerald-500/30 space-y-2">
                  <div className="flex items-center gap-2 font-mono text-xs font-bold text-emerald-400">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span>Data Safety & Zero Tracking</span>
                  </div>
                  <ul className="text-xs text-slate-300 space-y-1 font-mono list-disc list-inside">
                    <li>100% Client-Side Local State</li>
                    <li>No analytics tracking or ad IDs</li>
                    <li>Local persistence via localStorage</li>
                    <li>Ed25519 & SHA-256 local WebCrypto</li>
                  </ul>
                </div>

                <div className="p-3.5 rounded-xl bg-slate-900/80 border border-emerald-500/30 space-y-2">
                  <div className="flex items-center gap-2 font-mono text-xs font-bold text-emerald-400">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span>Offline Performance & Resilience</span>
                  </div>
                  <ul className="text-xs text-slate-300 space-y-1 font-mono list-disc list-inside">
                    <li>Service Worker sw.js active</li>
                    <li>Zero external runtime dependencies</li>
                    <li>Framer Motion smooth 60fps HUD</li>
                    <li>WCAG AA high contrast dark theme</li>
                  </ul>
                </div>
              </div>

              <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono font-bold text-white uppercase">App Store Reviewer Notes:</span>
                  <button
                    type="button"
                    onClick={() => handleCopy("This app operates entirely offline and performs local privacy signal management and camera/mic spectrum obfuscation on-device. No user data is transmitted.", 'reviewerNotes')}
                    className="px-2 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 text-[10px] font-mono rounded cursor-pointer transition flex items-center gap-1"
                  >
                    {copiedField === 'reviewerNotes' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    Copy Notes
                  </button>
                </div>
                <p className="text-xs font-mono text-slate-300 bg-slate-950 p-2.5 rounded border border-slate-850">
                  "This app operates entirely offline and performs local privacy signal management and camera/mic spectrum obfuscation on-device. No user data is transmitted."
                </p>
              </div>
            </div>
          )}

          {activeTab === 'privacy_policy' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between bg-slate-900/80 p-3 rounded-xl border border-slate-800">
                <div>
                  <span className="text-xs font-mono font-bold text-white">App Store Privacy Compliance File</span>
                  <p className="text-xs text-slate-400">Download formatted Privacy Policy Markdown for App Store Connect & Play Console links.</p>
                </div>
                <button
                  type="button"
                  onClick={handleDownloadPrivacyPolicy}
                  className="px-3.5 py-1.5 bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 border border-emerald-500/40 rounded-lg text-xs font-mono font-bold flex items-center gap-1.5 cursor-pointer transition"
                >
                  <Download className="w-4 h-4" />
                  Download PRIVACY_POLICY.md
                </button>
              </div>

              <div className="p-4 bg-slate-950 rounded-xl border border-slate-850 text-xs font-mono space-y-2 text-slate-300 max-h-60 overflow-y-auto">
                <p className="text-emerald-400 font-bold"># PRIVACY NUTRITION LABEL (DATA NOT COLLECTED)</p>
                <p>- Biometric Data: Processed strictly in local GPU memory during camera overlay, never saved or uploaded.</p>
                <p>- Location Data: Processed strictly in local browser memory for map perimeter calculation.</p>
                <p>- Identifiers: Anonymous local rotating ID (e.g. {citizenState.anonymousId}) renewed every 120s.</p>
              </div>
            </div>
          )}

          {activeTab === 'metadata' && (
            <div className="space-y-3 font-mono text-xs">
              {Object.entries(appStoreMetadata).map(([key, val]) => (
                <div key={key} className="bg-slate-900/60 p-3 rounded-xl border border-slate-800 space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="text-slate-400 uppercase text-[10px] font-bold">{key.replace(/([A-Z])/g, ' $1')}</span>
                    <button
                      type="button"
                      onClick={() => handleCopy(val, key)}
                      className="px-2 py-0.5 bg-slate-800 hover:bg-slate-700 text-slate-300 text-[9px] rounded cursor-pointer transition flex items-center gap-1"
                    >
                      {copiedField === key ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                      Copy
                    </button>
                  </div>
                  <div className="text-slate-200 bg-slate-950 p-2 rounded border border-slate-850 text-xs font-semibold">
                    {val}
                  </div>
                </div>
              ))}
            </div>
          )}

          {activeTab === 'export_compliance' && (
            <div className="space-y-4 font-mono text-xs">
              <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-white uppercase text-xs">US Export Compliance (EAR99 / Mass Market Encryption):</span>
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-cyan-500/20 text-cyan-300 border border-cyan-500/40">
                    EXEMPT (CATEGORY 5 PART 2)
                  </span>
                </div>
                <p className="text-slate-300 text-xs leading-relaxed">
                  BlurBubble uses standard browser WebCrypto API calls (SHA-256 and Ed25519) strictly for local data integrity and RFC-9402 signal signatures. Under US BIS EAR §740.17(b), standard web-browser cryptographic calls do not require a separate CCATS export classification.
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-900/90 border-t border-slate-800 flex items-center justify-between text-xs font-mono">
          <span className="text-slate-400">BlurBubble Build v2.4.0 (PWA & Native Container Compatible)</span>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-1.5 bg-emerald-500 text-slate-950 hover:bg-emerald-400 font-bold rounded-lg cursor-pointer transition"
          >
            Close & Launch App
          </button>
        </div>
      </motion.div>
    </div>
  );
};
